name: mp_file
description: The mpflutter file api.
publish_to: none
version: 0.3.0
homepage: /

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter: ">=0.19.0"
  mpcore: ">=0.19.0"

dependency_overrides:
  # flutter: ">=0.11.0"
  # mpcore: ">=0.11.0"
  # flutter:
  #   path: /Users/saiakirahui/Documents/mpflutter/mpflutter/packages/flutter
  # mpcore:
  #   path: /Users/saiakirahui/Documents/mpflutter/mpflutter/packages/mpcore
