name: mp_file
description: The mpflutter file api.
publish_to: none
version: 0.0.3
homepage: /

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter: ">0.16.4"
  mpcore: ">0.16.4"

dependency_overrides:
  # flutter: ">=0.11.0"
  # mpcore: ">=0.11.0"
  flutter:
    path: /Users/saiakirahui/Documents/mpflutter/mpflutter/packages/flutter
  mpcore:
    path: /Users/saiakirahui/Documents/mpflutter/mpflutter/packages/mpcore
