name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload To Private Pub
      uses: mpflutter/mp-pub-action@master
      with:
        secret_id: ${{ secrets.COS_SECRET_ID }}
        secret_key: ${{ secrets.COS_SECRET_KEY }}
        cos_bucket: mpflutter-dist-1253771526
        cos_region: ap-guangzhou
        package_name: mp_file
        package_path: ./